backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
locale: "pt"
media_folder: public/posts
public_folder: posts
collections:
  - name: "header"
    label: "Header"      
    folder: "public/posts/header"
    identifier_field: "label"
    slug: "{{slug}}"
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "label", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "exemplo"
    label: "Exemplo"      
    folder: "public/posts/exemplo"
    identifier_field: "nome"
    slug: "{{slug}}"
    extension: "json"    
    create: true
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "nome", widget: "string" }