backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
locale: "pt"
media_folder: public/posts
public_folder: posts
collections:
  - name: "Menus"
    label: "menus"
    folder: "public/posts/menus"
    media_folder: "menus.json"
    create: false    
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "label", widget: "string" }      
  - name: "exemplo"
    label: "Exemplo"      
    folder: "public/posts/exemplo"
    identifier_field: "nome"
    slug: "{{slug}}"
    extension: "json"    
    create: true
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "nome", widget: "string" }